[package]
name = "tui-tetris"
version = "0.1.0"
authors = ["zdravko"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rand_derive = "0.5"
termion = "1.5"
tui = "0.12"
delegate = "0.13.3"
syn = "2"

